version: 0
metadata:
  name: imbstack.com
  description: personal website
  owner: '{{ event.head.user.email }}'
  source: '{{ event.head.repo.url }}'
tasks:
  - provisionerId: '{{ taskcluster.docker.provisionerId }}'
    workerType: '{{ taskcluster.docker.workerType }}'
    extra:
      github:
        branches:
          - master
        events:
          - push
    scopes:
      - secrets:get:repo:github.com/imbstack/imbstack.com
    payload:
      features:
        taskclusterProxy: true
      maxRunTime: 3600
      image: 'imbstack/jekyll-s3'
      env:
        JEKYLL_ENV: production
      command:
        - '/bin/bash'
        - '--login'
        - '-c'
        - >-
          git clone {{event.head.repo.url}} repo && cd repo && git checkout {{event.head.sha}} && make website-push
    metadata:
      name: Upload to S3
      description: Run Jekyll and upload Site
      owner: '{{ event.head.user.email }}'
      source: '{{ event.head.repo.url }}'

