title: Brian Stack
description: >
  Brian does things and writes about some of them.
baseurl: ""
url: "http://imbstack.com"
author: bstack

# Build settings
markdown: kramdown

gems:
  - jekyll-feed

exclude:
  - Dockerfile
  - Makefile
  - Gemfile
  - Gemfile.lock
  - README.md
  - push.sh
