title: imbstack
description: imbstack does things with computers.
baseurl: ""
url: "https://imbstack.com"
author: bstack

# Build settings
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-assets

exclude:
  - Dockerfile
  - Makefile
  - Gemfile
  - Gemfile.lock
  - README.md
  - push.sh
  - extra
