title: Brian Stack
description: Brian Stack does things with computers.
baseurl: ""
url: "https://imbstack.com"
author: bstack

# Build settings
markdown: kramdown

gems:
  - jekyll-feed

exclude:
  - Dockerfile
  - Makefile
  - Gemfile
  - Gemfile.lock
  - README.md
  - push.sh
  - extra
